import { Banknote, Building2, CalendarDays, CircleDollarSign, ReceiptText, TicketCheck, WalletCards } from 'lucide-react';
import { PlatformMetricCard } from '@/features/super-admin/components/PlatformMetricCard';
import { fetchPlatformOverview } from '@/features/super-admin/api/server';

const currency = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });
const compact = new Intl.NumberFormat('pt-BR', { notation: 'compact', maximumFractionDigits: 1 });

export default async function SuperAdminOverviewPage() {
  const data = await fetchPlatformOverview();
  const maxGross = Math.max(...data.topOrganizers.map((item) => item.gross), 1);

  return <div className="space-y-8">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-violet-700">Visão geral</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Saúde do ecossistema</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Receita, operação e valores a repassar consolidados em uma única visão.</p></div><div className={`w-fit rounded-full px-3 py-1.5 text-xs font-semibold ${data.provider === 'mock' ? 'bg-amber-50 text-amber-700' : 'bg-emerald-50 text-emerald-700'}`}>{data.provider === 'mock' ? 'Gateway em simulação local' : 'AbacatePay conectado'}</div></header>
    <section aria-label="Indicadores principais" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <PlatformMetricCard label="Volume vendido" value={currency.format(data.metrics.grossRevenue)} helper={`${compact.format(data.metrics.ticketsSold)} ingressos pagos`} icon={CircleDollarSign} tone="emerald" />
      <PlatformMetricCard label="Receita da plataforma" value={currency.format(data.metrics.platformRevenue)} helper={`${currency.format(data.metrics.providerFees)} em tarifas do gateway`} icon={Banknote} />
      <PlatformMetricCard label="Saldo dos organizadores" value={currency.format(data.metrics.organizerPayable)} helper="Valor líquido ainda disponível para repasse" icon={WalletCards} tone="blue" />
      <PlatformMetricCard label="Organizadores ativos" value={`${data.metrics.activeOrganizers}/${data.metrics.organizers}`} helper={`${data.metrics.publishedEvents} eventos publicados`} icon={Building2} tone="amber" />
    </section>
    <section className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]">
      <div className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Organizadores por volume</h2><p className="mt-1 text-sm text-slate-500">Quem mais movimenta a plataforma.</p></div><Building2 className="size-5 text-slate-400" /></div><div className="mt-6 space-y-5">{data.topOrganizers.length ? data.topOrganizers.map((item, index) => <div key={item.id}><div className="mb-2 flex items-center justify-between gap-4 text-sm"><div className="min-w-0"><span className="mr-2 text-xs font-semibold text-slate-400">0{index + 1}</span><span className="font-medium text-slate-900">{item.name}</span><span className="ml-2 text-xs text-slate-500">{item.events} eventos</span></div><span className="shrink-0 font-semibold">{currency.format(item.gross)}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-blue-500" style={{ width: `${Math.max(4, item.gross / maxGross * 100)}%` }} /></div></div>) : <p className="py-10 text-center text-sm text-slate-500">As vendas aparecerão aqui.</p>}</div></div>
      <div className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-semibold">Operação agora</h2><p className="mt-1 text-sm text-slate-500">Itens que ajudam a dimensionar o ecossistema.</p><div className="mt-6 grid grid-cols-2 gap-3">{[{ label: 'Eventos', value: data.metrics.events, icon: CalendarDays }, { label: 'Publicados', value: data.metrics.publishedEvents, icon: TicketCheck }, { label: 'Ingressos', value: data.metrics.ticketsSold, icon: ReceiptText }, { label: 'Organizadores', value: data.metrics.organizers, icon: Building2 }].map((item) => { const Icon = item.icon; 

return <div key={item.label} className="rounded-lg bg-slate-50 p-4"><Icon className="size-5 text-violet-600" /><p className="mt-3 text-2xl font-bold">{compact.format(item.value)}</p><p className="text-xs text-slate-500">{item.label}</p></div>; })}</div></div>
    </section>
    <section className="rounded-lg border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-6"><h2 className="font-semibold">Transações recentes</h2><p className="mt-1 text-sm text-slate-500">Últimas confirmações e movimentações do gateway.</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-3">Participante</th><th className="px-6 py-3">Evento</th><th className="px-6 py-3">Organizador</th><th className="px-6 py-3">Status</th><th className="px-6 py-3 text-right">Valor</th></tr></thead><tbody className="divide-y divide-slate-100">{data.recentTransactions.map((transaction) => <tr key={transaction.id} className="hover:bg-slate-50"><td className="px-6 py-4 font-medium">{transaction.registration_id?.participant_name ?? '—'}</td><td className="px-6 py-4 text-slate-600">{transaction.registration_id?.event_id?.title ?? '—'}</td><td className="px-6 py-4 text-slate-600">{transaction.registration_id?.event_id?.organizer_id?.name ?? '—'}</td><td className="px-6 py-4"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">{transaction.status}</span></td><td className="px-6 py-4 text-right font-semibold">{currency.format(Number(transaction.amount ?? 0))}</td></tr>)}</tbody></table>{!data.recentTransactions.length && <p className="p-10 text-center text-sm text-slate-500">Nenhuma transação registrada.</p>}</div></section>
  </div>;
}

