import { Banknote, CircleDollarSign, ReceiptText, WalletCards } from 'lucide-react';
import { fetchPlatformOrganizers, fetchPlatformPayouts, fetchPlatformTransactions } from '@/features/super-admin/api/server';
import { PlatformMetricCard } from '@/features/super-admin/components/PlatformMetricCard';
import { PayoutCreationPanel } from '@/features/super-admin/components/PayoutCreationPanel';

const currency = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' });

export default async function PlatformFinancePage() {
  const [transactions, payouts, organizers] = await Promise.all([fetchPlatformTransactions(), fetchPlatformPayouts(), fetchPlatformOrganizers('limit=100&status=active')]);
  const succeeded = transactions.data.filter((item) => item.status === 'succeeded');
  const gross = succeeded.reduce((sum, item) => sum + Number(item.amount ?? 0), 0);
  const platform = succeeded.reduce((sum, item) => sum + Number(item.platform_fee ?? 0), 0);
  const provider = succeeded.reduce((sum, item) => sum + Number(item.provider_fee ?? 0), 0);
  const net = succeeded.reduce((sum, item) => sum + Number(item.organizer_net ?? 0), 0);
  const enabledOrganizers = organizers.data.filter((item) => item.payout_status === 'enabled').map((item) => ({ id: item.id, name: item.name }));

  return <div className="space-y-8"><header><p className="text-sm font-semibold text-violet-700">Financeiro global</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Fluxo financeiro da plataforma</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Conciliação de vendas, tarifas do gateway, receita da plataforma e compromissos com organizadores.</p></header>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><PlatformMetricCard label="Volume processado" value={currency.format(gross)} helper={`${succeeded.length} transações confirmadas`} icon={CircleDollarSign} tone="emerald" /><PlatformMetricCard label="Receita da plataforma" value={currency.format(platform)} helper="Taxas de serviço reconhecidas" icon={Banknote} /><PlatformMetricCard label="Custo do gateway" value={currency.format(provider)} helper="Tarifas informadas pelo provedor" icon={ReceiptText} tone="amber" /><PlatformMetricCard label="Líquido dos organizadores" value={currency.format(net)} helper="Antes dos repasses já realizados" icon={WalletCards} tone="blue" /></section>
    <PayoutCreationPanel organizers={enabledOrganizers} />
    <section className="grid gap-6 xl:grid-cols-[1.4fr_0.8fr]"><div className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5"><h2 className="font-semibold">Conciliação de transações</h2><p className="text-xs text-slate-500">Valores brutos, tarifas e líquido por venda.</p></div><div className="max-h-[620px] overflow-auto"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Operação</th><th className="px-5 py-3">Organizador</th><th className="px-5 py-3 text-right">Bruto</th><th className="px-5 py-3 text-right">Gateway</th><th className="px-5 py-3 text-right">Líquido</th></tr></thead><tbody className="divide-y divide-slate-100">{transactions.data.map((item) => <tr key={item.id}><td className="px-5 py-4"><p className="font-medium">{item.registration_id?.event_id?.title ?? 'Evento'}</p><p className="text-xs text-slate-500">{item.registration_id?.participant_name ?? '—'} · {item.status}</p></td><td className="px-5 py-4 text-slate-600">{item.registration_id?.event_id?.organizer_id?.name ?? '—'}</td><td className="px-5 py-4 text-right font-medium">{currency.format(Number(item.amount ?? 0))}</td><td className="px-5 py-4 text-right text-amber-700">-{currency.format(Number(item.provider_fee ?? 0))}</td><td className="px-5 py-4 text-right font-semibold text-emerald-700">{currency.format(Number(item.organizer_net ?? 0))}</td></tr>)}</tbody></table>{!transactions.data.length && <p className="p-10 text-center text-sm text-slate-500">Nenhuma transação.</p>}</div></div>
    <div className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-5"><h2 className="font-semibold">Repasses recentes</h2><p className="text-xs text-slate-500">Histórico de transferências PIX.</p></div><div className="divide-y divide-slate-100">{payouts.data.map((payout) => <div key={payout.id} className="p-5"><div className="flex items-center justify-between gap-3"><p className="font-medium">{payout.organizer_id?.name ?? 'Organizador'}</p><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold">{payout.status}</span></div><p className="mt-2 text-lg font-bold">{currency.format(Number(payout.amount))}</p><p className="mt-1 text-xs text-slate-500">{new Date(payout.requested_at).toLocaleString('pt-BR')}</p></div>)}{!payouts.data.length && <p className="p-10 text-center text-sm text-slate-500">Nenhum repasse realizado.</p>}</div></div></section>
  </div>;
}

